import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :bookmark, BookmarkWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  url: [host: "https://marquee.fly.dev"]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Bookmark.Finch

config :bookmark, Bookmark.Mailer,
  adapter: Swoosh.Adapters.AmazonSES,
  region: "us-east-1",
  access_key: {:system, "SMTP_USERNAME"},
  secret: {:system, "SMTP_PASSWORD"}

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
