services:
  app:
    build:
      context: ./app
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: bookmark
      PGPORT: 5432
      PGHOST: db
      SENDGRID_API_KEY_FILE: /run/secrets/SENDGRID_API_KEY
    secrets:
      - SENDGRID_API_KEY
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./app:/srv/www
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

secrets:
  SENDGRID_API_KEY:
    file: ./.sendgrid_api_key
